# Generated by Django 5.1.6 on 2025-02-11 17:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grateful_students', models.PositiveIntegerField(default=0, verbose_name='Кількість вдячних студентів')),
                ('diplomas', models.PositiveIntegerField(default=0, verbose_name='Кількість грамот')),
                ('articles_count', models.PositiveIntegerField(default=0, verbose_name='Кількість статей')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назва тегу')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Зміст')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('image', models.ImageField(upload_to='articles/', verbose_name='Зображення')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публікації')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='app.tag', verbose_name='Теги')),
            ],
        ),
    ]
